export enum AppItem {
	DASHBOARD = 'DASHBOARD',
	CREATE_TASK = 'CREATE_TASK',
	BOARD = 'BOARD',
	TRASH_BIN = 'TRASH_BIN',
	IMPORT_TASKS = 'IMPORT_TASKS',
	STATS = 'STATS',
	PROJECT_SETTINGS = 'PROJECT_SETTINGS',
	USER_SETTINGS = 'ACCOUNT_SETTINGS'
}